server:
  port: 8015


spring:
  application:
    name: heihei
  datasource:
    url: jdbc:mysql://localhost:3306/mysqlpractice
    username: root
    password: liguanda123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChinaFLTV/SpringCloudStudy_config.git
          search-paths:
            - SpringCloudStudy_config
      label: master

eureka:
  client:
    #true表示向注册中心注册自己，默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka8003.com:8003/eureka,http://eureka8004.com:8004/eureka
  instance:
    instance-id: config8015
    prefer-ip-address: true
